### ISSUE TITLE
Missing CI/CD workflows despite badge in README

### ISSUE THREAD

**Issue by democratize-technology-code-reviewer** [democratize-technology/node-red-contrib-open-food-facts#4]
## Issue Description
The README.md displays a GitHub Actions CI badge:
```markdown
[![Node.js CI](https://github.com/democratize-technology/node-red-contrib-open-food-facts/actions/workflows/ci.yml/badge.svg)](https://github.com/democratize-technology/node-red-contrib-open-food-facts/actions/workflows/ci.yml)
```

However, there is no `.github/workflows` directory or `ci.yml` file in the repository. This is misleading to users and contributors.

## Impact
- False sense of quality assurance
- No automated testing on pull requests
- No automated npm publishing
- Manual testing burden

### 1. Create `.github/workflows/ci.yml`:
```yaml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run lint # (need to add this script)
```

### 2. Add npm scripts to package.json:
```json
"scripts": {
    "test": "node --test test-openfoodfacts-api.js",
    "lint": "eslint *.js",
    "format": "prettier --write *.js",
    "prepare": "npm run lint && npm test"
}
```

### 3. Add development dependencies:
```json
"devDependencies": {
    "eslint": "^8.57.0",
    "prettier": "^3.2.5"
}
```

## Additional Workflow Suggestions
- Add semantic-release for automated npm publishing
- Add dependabot for dependency updates
- Add code coverage reporting
- Add Node-RED specific testing
